# BetterHorses config

# Configure custom aliases for the /horse command
command-aliases:
  # - bh
  # - horses

# Customizes how big the maximum positive or negative mutation effect is (e.g. 0.05 = Â±0.05)
# e.g. health-factor 3 means the health of the child can be up to 3 HP higher or lower than the average HP of both parents
mutation-factor:
  health: 3.0
  speed: 0.05
  jump: 0.05

# Max stats a horse can reach
max-stats:
  health: 300.0
  speed: 0.4
  jump: 1.2

# Settings that determine horse growth
horse-growth-settings:

  # If false, horses will remain their Vanilla size, this feature only works for Paper 1.20.6 & Java 21 or above
  enabled: true

  # The time in minutes that needs to pass until a horse is fully grown
  time-until-adult: 3

  # The maximum size a horse can reach, this is the scale applied to a vanilla sized horse
  # If the value remains 1, an adult horse will be vanilla sized
  max-size: 1.3 # 30% bigger than vanilla

# General settings
settings:

  # Customizes the original item a horse item is
  horse-item: SADDLE

  # Allow additional mount types to be treated like BetterHorses horses
  mount-types:
    skeleton-horses: false
    zombie-horses: false
    camels: false

  # Allows two horses of the same gender to breed
  allow-same-gender-breeding: false

  # Allows spawning the horse by rightclicking with the horse item
  allow-rightclick-spawn: true

  # If enabled, players riding a horse cant be hit
  rider-invulnerable: false

  # Fixes a vanilla bug where horses cant automatically climb from a path block onto a full block
  # because it exceeds their 1-block step height, only applies to mounted horses
  fix-step-height: true

  # Increases player melee damage by the given percentage while riding a horse
  mounted-damage-boost:
    enabled: false
    percentage: 25.0 # 25% more damage while mounted

  # Traited horses will have particles around them, disabling this will result in slightly better performance
  trait-particle-indicator: true

  # The amount of time in seconds that a horse needs before it can breed again (set to 0 for no cooldown)
  breeding-cooldown: 300 # 5 minutes

  # If true, male horses will ignore the breeding cooldown
  male-ignore-cooldown: true

  cooldown-display:
    # If false, the trait cooldown isn't displayed at all
    enabled: true

    # If true, the trait cooldown is shown as a bossbar when using an ability that is currently on cooldown
    show-bossbar-indicator: false

    # If true, the trait cooldown is shown above the hotbar when using an ability that is currently on cooldown
    show-hotbar-indicator: true

# Horse Abilities
traits:
  # Set this to false to disable the whole trait feature
  enabled: true

  hellmare:
    enabled: true
    chance: 0.005 # 0.5%
    duration: 5
    cooldown: 90
    radius: 2 # Radius of the fire below the horse

  fireheart:
    enabled: true
    chance: 0.01 # 1%

  dashboost:
    enabled: true
    chance: 0.01 # 1%
    duration: 10
    cooldown: 30

  featherhooves:
    enabled: true
    chance: 0.01 # 1%

  frosthooves:
    enabled: true
    chance: 0.005 # 0.5%
    radius: 3 # Radius of the ice below the horse

  kickback:
    enabled: true
    chance: 0.005 # 0.5%
    radius: 4
    strength: 6
    cooldown: 20

  ghosthorse:
    enabled: true
    chance: 0.005 # 0.5%
    duration: 5
    cooldown: 30

  skyburst:
    enabled: true
    chance: 0.003 # 0.3%
    radius: 4

  revenantcurse:
    enabled: true
    chance: 0.005 # 0.5%
    cooldown: 30
    duration: 10

  heavenhooves:
    enabled: true
    chance: 0.001 # 0.1%
    strength: 0.4
    particles: true
